# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 680, 480))
        self.tabs.setObjectName("tabs")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.labelName = QtWidgets.QLabel(self.tab1)
        self.labelName.setGeometry(QtCore.QRect(20, 30, 150, 30))
        self.labelName.setObjectName("labelName")
        self.LineEditName = QtWidgets.QLineEdit(self.tab1)
        self.LineEditName.setGeometry(QtCore.QRect(180, 30, 200, 30))
        self.LineEditName.setObjectName("LineEditName")
        self.labelHeight = QtWidgets.QLabel(self.tab1)
        self.labelHeight.setGeometry(QtCore.QRect(20, 80, 150, 30))
        self.labelHeight.setObjectName("labelHeight")
        self.LineEditHeight = QtWidgets.QLineEdit(self.tab1)
        self.LineEditHeight.setGeometry(QtCore.QRect(180, 80, 200, 30))
        self.LineEditHeight.setObjectName("LineEditHeight")
        self.labelWeight = QtWidgets.QLabel(self.tab1)
        self.labelWeight.setGeometry(QtCore.QRect(20, 130, 150, 30))
        self.labelWeight.setObjectName("labelWeight")
        self.LineEditWeight = QtWidgets.QLineEdit(self.tab1)
        self.LineEditWeight.setGeometry(QtCore.QRect(180, 130, 200, 30))
        self.LineEditWeight.setObjectName("LineEditWeight")
        self.BtnCalculate = QtWidgets.QPushButton(self.tab1)
        self.BtnCalculate.setGeometry(QtCore.QRect(180, 180, 200, 40))
        self.BtnCalculate.setObjectName("BtnCalculate")
        self.LblBMI = QtWidgets.QLabel(self.tab1)
        self.LblBMI.setGeometry(QtCore.QRect(180, 240, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LblBMI.setFont(font)
        self.LblBMI.setObjectName("LblBMI")
        self.tabs.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.TableHistory = QtWidgets.QTableWidget(self.tab2)
        self.TableHistory.setGeometry(QtCore.QRect(10, 10, 660, 430))
        self.TableHistory.setObjectName("TableHistory")
        self.TableHistory.setColumnCount(5)
        self.TableHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableHistory.setHorizontalHeaderItem(4, item)
        self.tabs.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ماشین حساب BMI"))
        self.labelName.setText(_translate("MainWindow", "نام کاربر:"))
        self.LineEditName.setPlaceholderText(_translate("MainWindow", "مثلاً Ali"))
        self.labelHeight.setText(_translate("MainWindow", "قد (سانتی‌متر - عدد صحیح):"))
        self.LineEditHeight.setPlaceholderText(_translate("MainWindow", "مثلاً 175"))
        self.labelWeight.setText(_translate("MainWindow", "وزن (کیلوگرم - عدد اعشاری):"))
        self.LineEditWeight.setPlaceholderText(_translate("MainWindow", "مثلاً 70.5"))
        self.BtnCalculate.setText(_translate("MainWindow", "محاسبه کن!"))
        self.LblBMI.setText(_translate("MainWindow", "BMI: ---"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab1), _translate("MainWindow", "محاسبه BMI"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab2), _translate("MainWindow", "تاریخچه"))
        self.TableHistory.horizontalHeaderItem(0).setText(_translate("MainWindow", "تاریخ"))
        self.TableHistory.horizontalHeaderItem(1).setText(_translate("MainWindow", "نام"))
        self.TableHistory.horizontalHeaderItem(2).setText(_translate("MainWindow", "قد"))
        self.TableHistory.horizontalHeaderItem(3).setText(_translate("MainWindow", "وزن"))
        self.TableHistory.horizontalHeaderItem(4).setText(_translate("MainWindow", "BMI"))
